let toastTimer: ReturnType<typeof setTimeout>;
const sidebarDetails = document.querySelector<HTMLDetailsElement>('.docs-sidebar details');
if (sidebarDetails && matchMedia('(max-width: 650px)').matches) sidebarDetails.open = false;
function notify(message: string) { const el = document.querySelector<HTMLElement>('#toast'); if (!el) return; el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3500); }
async function copy(text: string) { try { await navigator.clipboard.writeText(text);notify('Copied to clipboard'); } catch { notify('Copy unavailable. Select the text and copy it manually.'); } }
document.querySelector('#theme-toggle')?.addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('getbible-theme',theme)}catch{};});
document.querySelector('#menu-toggle')?.addEventListener('click',event=>{const nav=document.querySelector('.main-nav');const open=nav?.classList.toggle('open');(event.currentTarget as HTMLElement).setAttribute('aria-expanded',String(open));});
document.querySelectorAll<HTMLElement>('[data-copy-target]').forEach(button=>button.addEventListener('click',()=>copy(document.getElementById(button.dataset.copyTarget||'')?.textContent||'')));
document.querySelectorAll<HTMLElement>('[data-copy]').forEach(button=>button.addEventListener('click',()=>copy(button.dataset.copy||'')));
document.querySelectorAll('[data-share]').forEach(button=>button.addEventListener('click',async()=>{const url=new URL(location.href);url.searchParams.delete('format');if(navigator.share){try{await navigator.share({title:document.title,url:url.href});}catch(error){if((error as Error).name!=='AbortError')await copy(url.href)}}else await copy(url.href)}));
document.querySelectorAll('.prose pre').forEach(pre=>{const wrapper=document.createElement('div');wrapper.className='code-wrapper';pre.before(wrapper);wrapper.append(pre);const button=document.createElement('button');button.type='button';button.className='copy-code';button.textContent='Copy';button.setAttribute('aria-label','Copy code example');button.addEventListener('click',()=>copy(pre.textContent||''));wrapper.append(button);});
document.querySelectorAll('.prose table').forEach(table=>{const wrapper=document.createElement('div');wrapper.className='table-wrapper';wrapper.tabIndex=0;wrapper.setAttribute('role','region');wrapper.setAttribute('aria-label','Scrollable reference table');table.before(wrapper);wrapper.append(table)});
let filter='All';const catalogQuery=document.querySelector<HTMLInputElement>('#catalog-query');
function filterCards(){let count=0;document.querySelectorAll<HTMLElement>('.project-card').forEach(card=>{const visible=(filter==='All'||card.dataset.category===filter)&&(!catalogQuery?.value||card.dataset.search?.includes(catalogQuery.value.toLowerCase()));card.hidden=!visible;if(visible)count++});const empty=document.querySelector<HTMLElement>('.catalog-empty');if(empty)empty.hidden=count>0;const output=document.querySelector('#catalog-count');if(output)output.textContent=`${count} projects shown`;}
document.querySelectorAll<HTMLElement>('[data-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter||'All';document.querySelectorAll<HTMLElement>('[data-filter]').forEach(x=>{x.classList.toggle('active',x===button);x.setAttribute('aria-pressed',String(x===button))});filterCards()}));catalogQuery?.addEventListener('input',filterCards);
const dialog=document.querySelector<HTMLDialogElement>('#search-dialog');const searchInput=document.querySelector<HTMLInputElement>('#docs-search');let searchIndex: {title:string;url:string;text:string;description:string}[]|null=null;let indexPromise:Promise<void>|null=null;
async function loadIndex(){if(searchIndex)return;if(!indexPromise)indexPromise=fetch('/search-index.json').then(r=>{if(!r.ok)throw Error('Failed to load index');return r.json()}).then(data=>{searchIndex=data}).finally(()=>indexPromise=null);return indexPromise;}
function openSearch(){dialog?.showModal();searchInput?.focus();}
document.querySelector('#search-open')?.addEventListener('click',openSearch);document.querySelector('#search-close')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close()}});document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='k'){event.preventDefault();openSearch();}});
let searchSequence=0;searchInput?.addEventListener('input',async()=>{const sequence=++searchSequence;const query=searchInput.value.toLowerCase().trim();const status=document.querySelector('#search-status')!;const results=document.querySelector('#search-results')!;results.replaceChildren();if(!query){status.textContent='Type to search APIs, projects and guides.';return}status.textContent='Searching…';try{await loadIndex();if(sequence!==searchSequence)return;const terms=query.split(/\s+/);const matches=(searchIndex||[]).map(item=>({item,score:terms.reduce((n,term)=>n+(item.title.toLowerCase().includes(term)?8:0)+(item.description.toLowerCase().includes(term)?3:0)+(item.text.toLowerCase().includes(term)?1:0),0)})).filter(({item})=>terms.every(term=>(item.title+' '+item.text).toLowerCase().includes(term))).sort((a,b)=>b.score-a.score).slice(0,15);status.textContent=matches.length?`${matches.length} matching pages`:'No matches. Try a different word.';matches.forEach(({item})=>{const link=document.createElement('a');link.href=item.url;link.className='search-result';const title=document.createElement('strong');title.textContent=item.title;const excerpt=document.createElement('span');const pos=item.text.toLowerCase().indexOf(terms[0]);excerpt.textContent=pos>=0?item.text.slice(Math.max(0,pos-55),pos+170).replace(/[#*`]/g,'')+'…':item.description;link.append(title,excerpt);results.append(link)});}catch{status.textContent='Search could not load. Use the API and project navigation, or try again.'}});
const markdownUrl=document.body.dataset.markdown;
async function showMarkdown(){if(!markdownUrl)return;const main=document.querySelector('main')!;try{const response=await fetch(markdownUrl);if(!response.ok)throw Error('Markdown unavailable');const markdown=await response.text();const section=document.createElement('section');section.className='markdown-view';const actions=document.createElement('div');actions.className='page-actions';const back=document.createElement('a');const url=new URL(location.href);url.searchParams.delete('format');back.href=url.pathname+url.search+url.hash;back.textContent='← Read formatted page';const raw=document.createElement('a');raw.href=markdownUrl;raw.textContent='Open raw .md';const button=document.createElement('button');button.type='button';button.textContent='Copy Markdown';button.addEventListener('click',()=>copy(markdown));actions.append(back,raw,button);const title=document.createElement('h1');title.textContent='Markdown documentation';const pre=document.createElement('pre');pre.textContent=markdown;section.append(actions,title,pre);main.replaceChildren(section);}catch{notify('Markdown could not load. Try the raw Markdown link.')}}
document.querySelectorAll<HTMLAnchorElement>('[data-markdown-toggle]').forEach(link=>{const url=new URL(location.href);url.searchParams.set('format','markdown');link.href=url.pathname+url.search;});if(new URLSearchParams(location.search).get('format')==='markdown')showMarkdown();
const tocLinks=[...document.querySelectorAll<HTMLAnchorElement>('.docs-toc a')];if('IntersectionObserver'in window&&tocLinks.length){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)tocLinks.forEach(link=>link.classList.toggle('active',link.hash==='#'+entry.target.id))},{rootMargin:'-100px 0px -65% 0px'});document.querySelectorAll('.prose h2,.prose h3').forEach(heading=>observer.observe(heading));}
